name: gamma_hdlm
type: ddit
hidden_size: 768
cond_dim: 128
length: 1024
n_blocks: 12
n_heads: 12
scale_by_sigma: True
dropout: 0.1
transformer_sigma_conditioning: True
hybrid_sigma_embedding: True
post_process_logits: True
use_timestep_embedding: True